//==============================================================================
// driver -- drives the generated byte stream into the DUT
//------------------------------------------------------------------------------
//  * One byte per clock, back to back, through the interface clocking block
//    (drv_cb): bytes change 1ns after the rising edge, so the DUT always
//    samples a stable value on the next edge (no race).
//  * Each byte is tagged with its stream index on the TB side band
//    (tb_byte_idx / tb_byte_valid) so checkpoints can be evaluated at the
//    right cycle.
//  * IK_RESET items assert the asynchronous reset in mid-stream: reset rises
//    and falls on a falling clock edge, away from the sampling edge (the
//    legacy testbench released reset exactly on a rising edge -> race).
//  * When the stream is exhausted the driver sends idle 0x00 bytes marked
//    tb_byte_valid = 0, so the input is never undriven or X.
//==============================================================================
class driver;

  virtual frame_inf      vif;
  std::mailbox #(transaction) gen2drv;

  int unsigned items_driven;
  int unsigned bytes_driven;
  bit          done;           // every queued item has been driven

  function new(virtual frame_inf vif, std::mailbox #(transaction) gen2drv);
    this.vif     = vif;
    this.gen2drv = gen2drv;
  endfunction

  // Initial reset: called at time 0, before the stream starts.
  // Timing uses only clocking-block events (see the rule in frame_inf.sv).
  task reset_dut(int unsigned cycles = 3);
    vif.reset         = 1'b1;
    vif.rx_data       = 8'h00;
    vif.tb_byte_idx   = 0;
    vif.tb_byte_valid = 1'b0;
    fa_info(1, "DRIVER", $sformatf("reset asserted for %0d cycles", cycles));
    repeat (cycles) @(vif.drv_cb);
    @(vif.rst_cb);
    vif.rst_cb.reset <= 1'b0;
    fa_info(1, "DRIVER", "reset released");
  endtask

  // One idle byte (not part of the stream).
  task drive_idle();
    @(vif.drv_cb);
    vif.drv_cb.rx_data       <= 8'h00;
    vif.drv_cb.tb_byte_valid <= 1'b0;
  endtask

  // Mid-stream asynchronous reset.  By default two idle bytes are sent first,
  // so that the DUT's response to the last stream byte is sampled (and its
  // checkpoints are evaluated) before the reset clears the outputs.  With
  // one idle byte the reset hits while the DUT still holds the state reached
  // with the last stream byte.
  task drive_reset(transaction tr);
    repeat (tr.reset_idle_before) drive_idle();
    @(vif.rst_cb);
    vif.rst_cb.reset <= 1'b1;
    fa_info(2, "DRIVER", $sformatf("%s: reset asserted", tr.label));
    repeat (tr.reset_cycles) drive_idle();
    @(vif.rst_cb);
    vif.rst_cb.reset <= 1'b0;
    fa_info(2, "DRIVER", $sformatf("%s: reset released", tr.label));
  endtask

  task drive_bytes(transaction tr);
    foreach (tr.frame[i]) begin
      @(vif.drv_cb);
      vif.drv_cb.rx_data       <= tr.frame[i];
      vif.drv_cb.tb_byte_idx   <= tr.first_byte_idx + i;
      vif.drv_cb.tb_byte_valid <= 1'b1;
      bytes_driven++;
      fa_info(3, "DRIVER", $sformatf("byte %0d = %02h", tr.first_byte_idx + i, tr.frame[i]));
    end
  endtask

  // Drive every queued item, then idle forever (the environment stops the
  // simulation once the pipeline has drained).
  task run();
    transaction tr;
    while (gen2drv.try_get(tr)) begin
      fa_info(2, "DRIVER", $sformatf("item %0d: %s", items_driven + 1, tr.label));
      if (tr.item_kind == transaction::IK_RESET) drive_reset(tr);
      else                                       drive_bytes(tr);
      items_driven++;
    end
    done = 1'b1;
    fa_info(1, "DRIVER", $sformatf("stream complete: %0d items, %0d bytes", items_driven, bytes_driven));
    forever drive_idle();
  endtask

endclass
